// Re-export shared types for client use
export type {
  UserProfile,
  BasicInfo,
  PersonalityDimensions,
  NarrativeDimensions,
  Trait,
  Confidence,
  MemoryEntry,
  MemoryType,
  Contradiction,
  RelationPerson,
  TimelineEvent,
  Evidence,
  ProfileVersion,
  Conversation,
  ConversationPhase,
  Message,
  MessageMetadata,
  InternalAnalysis,
  ChatRequest,
  ChatResponse,
  ProfileResponse,
} from '../../../shared/types';
